# -*- coding: utf-8 -*-
"""Copy of Copy of Copy of Copy of LSDS Intro Assignment 1 - Getting Started with Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZSj8I3C-cS08n-mcFW2nHBHpBCnSN8QZ

# Lambda School Data Science - Getting Started with Python

Following are exercises you should complete after watching the first intro lecture. Workflow:

1. Sign in to a Google account
2. Copy the notebook (`File` -> `Save a copy in Drive`)
3. Complete the exercises! This means fill out the code cells, and run them (shift-enter or click the play button that appears when you're in one of them)
4. Take a look at your work, and write comments/add text cells as appropriate to explain
5. Make the notebook URL viewable and submit with the standup form

## Exercise 1 - A bit of Math

For these "word" problems, use Python to clearly solve them. Your code will "show your work" - use good variable names! To show your answers you should write a `print()` statement at the end.

As you work, follow the **20 minute rule** - that means if you're stuck on something for 20 minutes, you should ask a question!

### a) It's a gas

A taxi driver is calculating their profit over two weeks by adding up the fares they charge and subtracting the cost of gas. The price of gas changes over time - it was `$3.52`/gallon the first week and `$3.57`/gallon this second week. Their car gets 20 miles per gallon.

For the first week the driver had a total of 23 passengers with average `$29` fare each, and drove a total of 160 miles. For the second week they had 17 passengers with average `$30` fare each, and drove a total of 220 miles. Assume that for both weeks they purchase all the gas needed during that week (i.e. they refuel every week to maintain a constant level of gas in the tank).

Based on the above, answer the following questions:

- What is their total profit over both weeks?
- During which week was their average (mean) profit per passenger higher?
"""

def total_profit (ppg, passengers, avg_fare, total_miles):
    mpg = 20
    
    total_exp = (total_miles / mpg) * ppg    
    total_rev = passengers * avg_fare      
    total_profit = total_rev - total_exp   
    avg_profit = total_profit / passengers 
    
    print('The total profit earned during this week is: ' + str(total_profit))
    print('The average profit earned during this week is: ' + str(avg_profit))
    
total_profit(3.52, 23, 29, 160)
total_profit(3.57, 17, 30, 220)

# Week 1 had a slightly higher average profit margin per passenger

"""### b) Mo' money...

A cash drawer contains 160 bills, all 10s and 50s. The total value of the 10s and 50s is $1,760.

How many of each type of bill are in the drawer? You can figure this out by trial and error (or by doing algebra with pencil and paper), but try to use loops and conditionals to check a plausible possibilities and stop when you find the correct one.
"""

def bill_counts (num_bills, total_value):
    d = {'x': 10, 'y': 50} # Dictionary containing dollar bill values for each note
      
    y = (total_value - num_bills *d['x']) / (d['y']-d['x']) # Algebra equation isolating y value
    
    x = num_bills - y # Isolating x value with y value known
    
    print("The total number of ten dollar bills is: " + str(x))
    print("The total number of fifty dollar bills is: " + str(y))

bill_counts(160,1760)

"""## Exercise 2 - Drawing a plot

Use NumPy and Matplotlib to draw a scatterplot of uniform random `(x, y)` values all drawn from the `[0, 1]` interval. Helpful documentation:

*   https://matplotlib.org/tutorials/index.html
*   https://docs.scipy.org/doc/numpy/user/quickstart.html

Stretch goal - draw more plots! You can refer to the [Matplotlib gallery](https://matplotlib.org/gallery.html) for inspiration, but don't just reproduce something - try to apply it to your own data.

How to get data? There's *many* ways, but a good place to get started is with [sklearn.datasets](http://scikit-learn.org/stable/datasets/index.html):

```
from sklearn import datasets
dir(datasets)
```
"""

import matplotlib.pyplot as plt
import numpy as np

x = np.random.uniform(0,1,100)
y = np.random.uniform(0,1,100)

plt.scatter(x,y)



"""## Exercise 3 - Writing a function
Write a function that, given a list of numbers, calculates the mean, median, and mode of those numbers. Return a dictionary with properties for the mean, median and mode. 

For example:

```
mmm_dict = meanMedianMode([1, 2, 6, 7, 8, 9, 3, 4, 5, 10, 10])
print(mmm_dict)
> {'mean': 5.909090909090909, 'median': 6, 'mode': 10}
```

There are Python standard libraries that make calculating these numbers very easy, but first try your hand at implementing it using the `reduce()` function:
"""

from functools import reduce
help(reduce)

from collections import Counter

def meanMedianMode(numbers):
    
    mmm_dict = {}
    
    #Mean ---------------------
     
    total_sum = reduce(lambda x, y: x+y, numbers)
    total_count = len(numbers)
    
    mean = total_sum / total_count
    
    mmm_dict['mean'] = mean
    
    #Median -------------------
    
    num_list = list(numbers)
    num_list.sort()
    
    if total_count % 2 == 0:
        
        med_high_index = int((total_count / 2)) 
        med_low_index = int((total_count / 2) - 1)
        
        med_high_num = num_list[med_high_index]
        med_low_num = num_list[med_low_index]
        
        median = (med_high_num + med_low_num) / 2  
    else:
        med_index = int(total_count / 2)
        median = num_list[med_index]
          
    mmm_dict['median'] = median
    
    #Mode ---------------------
    
    for num in num_list:
        data = Counter(num_list)       
        mode = max(num_list, key=data.get)
    
    mmm_dict['mode'] = mode
    
    print(mmm_dict)

meanMedianMode([1, 2, 6, 7, 8, 9, 3, 4, 5, 10, 10])

